# Site Identity & Information
title: "Joya Rent Car - Sewa Mobil Mudah & Terpercaya"
tagline: "Berkendara Lebih Nyaman & Elegan"
description: "Penyedia jasa rental mobil profesional & terpercaya. Melayani sewa mobil lepas kunci maupun plus driver untuk kebutuhan dinas, instansi, dan perorangan."
url: "https://sudut-nirwana.github.io"
baseurl: "/joya-rentcar-demo"

# Build & Markdown Settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# SCSS Compression Settings
sass:
  sass_dir: _sass
  style: compressed

# Active Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Excluded Files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .git/
  - .gitignore
